# Generated by Django 3.2.12 on 2022-02-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220224_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.TextField(default='todo_default', max_length=64),
            preserve_default=False,
        ),
    ]
